# Generated by Django 5.1.5 on 2025-01-18 18:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blogpost',
            old_name='updated_ar',
            new_name='updated_at',
        ),
    ]
